name: "Deploy Trymai Docker Image"
description: "Deploy Trymai Docker Image"
inputs:
  google-credentials:
    description: "e.g. ${{ secrets.GOOGLE_CREDENTIALS }}"
    required: true
  trymai-cluster-name:
    description: "e.g. trymai-stage"
    required: true
  trymai-project-id:
    description: "e.g. mimetic-wharf-336310"
    required: true
  trymai-cluster-zone:
    description: "e.g. europe-central2-a"
    required: true
  trymai-docker-registry:
    description: "e.g. europe-central2-docker.pkg.dev"
    required: true
  trymai-docker-repository:
    description: "e.g. trymai-docker-stage"
    required: true
  trymai-helm-repository:
    description: "e.g. trymai-helm-stage"
    required: true
  helm-charts-path:
    description: "e.g. ./.k8s/helm"
    required: true
    default: "./.k8s/helm"
  service-name:
    description: "e.g. ${{ env.SERVICE_NAME }}"
    required: true
  service-version:
    description: "e.g. ${{ env.SERVICE_VERSION }}"
    required: true
runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.google-credentials }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0

    - name: Get the Google Kubernetes Engine Credentials
      run: gcloud container clusters get-credentials ${{ inputs.trymai-cluster-name }} --zone ${{ inputs.trymai-cluster-zone }}
      shell: bash

    - name: Authenticate Docker with Google Artifact Registry.
      run: cat $GOOGLE_APPLICATION_CREDENTIALS | docker login -u _json_key --password-stdin https://${{ inputs.trymai-docker-registry }}
      shell: bash

    - name: Publish Docker Image
      run: docker push ${{ inputs.trymai-docker-registry }}/${{ inputs.trymai-project-id }}/{{ inputs.trymai-docker-repository }}/${{ inputs.service-name }}:${{ inputs.service-version }}
      shell: bash

    - name: Setup Helm
      uses: azure/setup-helm@v1

    - name: Lint Helm Charts
      run: helm lint --set service.name=${{ inputs.service-name }} --set service.version=${{ inputs.service-version }} ${{ inputs.helm-charts-path }}
      shell: bash

    - name: Publish Helm Charts
      run: |-
        helm package --version=${{ inputs.service-version }} --app-version=${{ inputs.service-version }} ${{ inputs.helm-charts-path }}
        helm push ${{ inputs.service-name }}-${{ inputs.service-version }}.tgz oci://${{ inputs.trymai-docker-registry }}/${{ inputs.trymai-project-id }}/${{ inputs.trymai-helm-repository }}
      shell: bash

    - name: Deploy image to the GKE cluster
      run: helm upgrade --install ${{ inputs.service-name }} oci://${{ inputs.trymai-docker-registry }}/${{ inputs.trymai-project-id }}/${{ inputs.trymai-helm-repository }}/${{ inputs.service-version }} --version ${{ inputs.service-version }} --set service.name=${{ inputs.service-version }} --set service.version=${{ inputs.service-version }}
      shell: bash